# -*- coding: utf-8 -*-
"""Infrastructure as Code Manager

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y1sEyvWd3UiDWmKNrdVAn4E3hqiXSSDK
"""

# iac_manager.py
# Infrastructure as Code Manager - Standalone Version
# No external dependencies required

import json
import hashlib
import logging
from typing import Dict, List, Optional, Any
from dataclasses import dataclass, asdict
from datetime import datetime
from pathlib import Path
from enum import Enum
import random

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

class DeploymentStatus(Enum):
    INITIALIZED = "initialized"
    PLANNING = "planning"
    APPLYING = "applying"
    APPLIED = "applied"
    FAILED = "failed"
    DESTROYED = "destroyed"

@dataclass
class TemplateFile:
    name: str
    content: str
    language: str
    checksum: str
    created_at: datetime

@dataclass
class DeploymentRecord:
    id: str
    environment: str
    template_name: str
    status: str
    resources_created: List[str]
    resources_destroyed: List[str]
    timestamp: datetime
    checksum: str
    version: str
    error_message: Optional[str] = None

@dataclass
class ResourceInfo:
    id: str
    type: str
    name: str
    deployment_id: str
    region: str
    tags: Dict[str, str]
    created_at: datetime
    status: str

class IaCTemplateGenerator:
    """Generates Infrastructure as Code templates"""

    @staticmethod
    def generate_terraform_template(config: Dict[str, Any]) -> str:
        """Generate a Terraform configuration file"""
        template = f'''# Terraform Configuration - Generated
# Environment: {config.get('environment', 'dev')}
# Project: {config.get('project', 'myproject')}
# Created: {datetime.now().isoformat()}

terraform {{
  required_version = ">= 1.0"
  required_providers {{
    aws = {{
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }}
  }}
}}

provider "aws" {{
  region = "{config.get('region', 'us-east-1')}"
}}

# Variables
variable "environment" {{
  type    = string
  default = "{config.get('environment', 'dev')}"
}}

variable "project_name" {{
  type    = string
  default = "{config.get('project', 'myproject')}"
}}

# EC2 Instance
resource "aws_instance" "app_server" {{
  ami           = "{config.get('ami', 'ami-0c55b159cbfafe1f0')}"
  instance_type = "{config.get('instance_type', 't2.micro')}"

  tags = {{
    Name        = "${{var.project_name}}-server"
    Environment = var.environment
    ManagedBy   = "Terraform"
  }}
}}

# Security Group
resource "aws_security_group" "app_sg" {{
  name        = "${{var.project_name}}-sg"
  description = "Security group for ${{var.project_name}}"

  ingress {{
    from_port   = 80
    to_port     = 80
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }}

  ingress {{
    from_port   = 443
    to_port     = 443
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }}

  egress {{
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }}

  tags = {{
    Environment = var.environment
  }}
}}

# Outputs
output "instance_id" {{
  value       = aws_instance.app_server.id
  description = "The ID of the EC2 instance"
}}

output "instance_public_ip" {{
  value       = aws_instance.app_server.public_ip
  description = "The public IP of the EC2 instance"
}}

output "security_group_id" {{
  value       = aws_security_group.app_sg.id
  description = "The ID of the security group"
}}
'''
        return template

    @staticmethod
    def generate_cloudformation_template(config: Dict[str, Any]) -> str:
        """Generate a CloudFormation template"""
        template = {
            "AWSTemplateFormatVersion": "2010-09-09",
            "Description": f"CloudFormation Template for {config.get('project', 'myproject')}",
            "Parameters": {
                "Environment": {
                    "Type": "String",
                    "Default": config.get('environment', 'dev'),
                    "AllowedValues": ["dev", "staging", "prod"]
                },
                "InstanceType": {
                    "Type": "String",
                    "Default": config.get('instance_type', 't2.micro')
                }
            },
            "Resources": {
                "AppInstance": {
                    "Type": "AWS::EC2::Instance",
                    "Properties": {
                        "ImageId": config.get('ami', 'ami-0c55b159cbfafe1f0'),
                        "InstanceType": {"Ref": "InstanceType"},
                        "Tags": [
                            {"Key": "Environment", "Value": {"Ref": "Environment"}},
                            {"Key": "ManagedBy", "Value": "CloudFormation"}
                        ]
                    }
                },
                "AppSecurityGroup": {
                    "Type": "AWS::EC2::SecurityGroup",
                    "Properties": {
                        "GroupDescription": f"Security group for {config.get('project', 'myproject')}",
                        "SecurityGroupIngress": [
                            {
                                "IpProtocol": "tcp",
                                "FromPort": "80",
                                "ToPort": "80",
                                "CidrIp": "0.0.0.0/0"
                            },
                            {
                                "IpProtocol": "tcp",
                                "FromPort": "443",
                                "ToPort": "443",
                                "CidrIp": "0.0.0.0/0"
                            }
                        ]
                    }
                }
            },
            "Outputs": {
                "InstanceId": {
                    "Description": "Instance ID",
                    "Value": {"Ref": "AppInstance"}
                },
                "SecurityGroupId": {
                    "Description": "Security Group ID",
                    "Value": {"Ref": "AppSecurityGroup"}
                }
            }
        }
        return json.dumps(template, indent=2)

    @staticmethod
    def generate_kubernetes_yaml(config: Dict[str, Any]) -> str:
        """Generate Kubernetes manifests"""
        template = f'''apiVersion: apps/v1
kind: Deployment
metadata:
  name: {config.get('app_name', 'app')}
  namespace: {config.get('namespace', 'default')}
  labels:
    app: {config.get('app_name', 'app')}
    environment: {config.get('environment', 'dev')}
spec:
  replicas: {config.get('replicas', 3)}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {config.get('app_name', 'app')}
  template:
    metadata:
      labels:
        app: {config.get('app_name', 'app')}
        version: {config.get('version', 'v1')}
    spec:
      containers:
      - name: {config.get('app_name', 'app')}
        image: {config.get('image', 'nginx:latest')}
        ports:
        - containerPort: {config.get('port', 8080)}
        resources:
          requests:
            memory: "{config.get('memory_request', '128Mi')}"
            cpu: "{config.get('cpu_request', '100m')}"
          limits:
            memory: "{config.get('memory_limit', '256Mi')}"
            cpu: "{config.get('cpu_limit', '500m')}"
        livenessProbe:
          httpGet:
            path: /health
            port: {config.get('port', 8080)}
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: {config.get('port', 8080)}
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: {config.get('app_name', 'app')}-service
  namespace: {config.get('namespace', 'default')}
spec:
  type: LoadBalancer
  selector:
    app: {config.get('app_name', 'app')}
  ports:
  - protocol: TCP
    port: 80
    targetPort: {config.get('port', 8080)}
'''
        return template

class IaCManager:
    """Main Infrastructure as Code Manager"""

    def __init__(self, base_dir: str = './infrastructure'):
        self.base_dir = Path(base_dir)
        self.base_dir.mkdir(parents=True, exist_ok=True)

        self.deployments_file = self.base_dir / 'deployments.json'
        self.resources_file = self.base_dir / 'resources.json'
        self.templates_file = self.base_dir / 'templates.json'

        self.deployments: List[DeploymentRecord] = self._load_deployments()
        self.resources: List[ResourceInfo] = self._load_resources()
        self.templates: Dict[str, TemplateFile] = self._load_templates()

        logger.info("IaC Manager initialized at: %s", self.base_dir)

    def _load_deployments(self) -> List[DeploymentRecord]:
        if not self.deployments_file.exists():
            return []

        try:
            with open(self.deployments_file, 'r') as f:
                data = json.load(f)
            return [
                DeploymentRecord(
                    id=d['id'],
                    environment=d['environment'],
                    template_name=d['template_name'],
                    status=d['status'],
                    resources_created=d.get('resources_created', []),
                    resources_destroyed=d.get('resources_destroyed', []),
                    timestamp=datetime.fromisoformat(d['timestamp']),
                    checksum=d['checksum'],
                    version=d.get('version', '1.0.0'),
                    error_message=d.get('error_message')
                )
                for d in data
            ]
        except Exception as e:
            logger.error("Error loading deployments: %s", e)
            return []

    def _load_resources(self) -> List[ResourceInfo]:
        if not self.resources_file.exists():
            return []

        try:
            with open(self.resources_file, 'r') as f:
                data = json.load(f)
            return [
                ResourceInfo(
                    id=r['id'],
                    type=r['type'],
                    name=r['name'],
                    deployment_id=r['deployment_id'],
                    region=r['region'],
                    tags=r.get('tags', {}),
                    created_at=datetime.fromisoformat(r['created_at']),
                    status=r['status']
                )
                for r in data
            ]
        except Exception as e:
            logger.error("Error loading resources: %s", e)
            return []

    def _load_templates(self) -> Dict[str, TemplateFile]:
        if not self.templates_file.exists():
            return {}

        try:
            with open(self.templates_file, 'r') as f:
                data = json.load(f)
            return {
                name: TemplateFile(
                    name=t['name'],
                    content=t['content'],
                    language=t['language'],
                    checksum=t['checksum'],
                    created_at=datetime.fromisoformat(t['created_at'])
                )
                for name, t in data.items()
            }
        except Exception as e:
            logger.error("Error loading templates: %s", e)
            return {}

    def _save_deployments(self):
        data = [
            {
                'id': d.id,
                'environment': d.environment,
                'template_name': d.template_name,
                'status': d.status,
                'resources_created': d.resources_created,
                'resources_destroyed': d.resources_destroyed,
                'timestamp': d.timestamp.isoformat(),
                'checksum': d.checksum,
                'version': d.version,
                'error_message': d.error_message
            }
            for d in self.deployments
        ]

        with open(self.deployments_file, 'w') as f:
            json.dump(data, f, indent=2)
        logger.info("Deployments saved to %s", self.deployments_file)

    def _save_resources(self):
        data = [
            {
                'id': r.id,
                'type': r.type,
                'name': r.name,
                'deployment_id': r.deployment_id,
                'region': r.region,
                'tags': r.tags,
                'created_at': r.created_at.isoformat(),
                'status': r.status
            }
            for r in self.resources
        ]

        with open(self.resources_file, 'w') as f:
            json.dump(data, f, indent=2)

    def _save_templates(self):
        data = {
            name: {
                'name': t.name,
                'content': t.content,
                'language': t.language,
                'checksum': t.checksum,
                'created_at': t.created_at.isoformat()
            }
            for name, t in self.templates.items()
        }

        with open(self.templates_file, 'w') as f:
            json.dump(data, f, indent=2)

    def calculate_checksum(self, content: str) -> str:
        return hashlib.sha256(content.encode()).hexdigest()

    def create_terraform_deployment(self, environment: str, config: Dict[str, Any]) -> Optional[str]:
        """Create a Terraform deployment"""
        deployment_id = f"tf-{environment}-{datetime.now().strftime('%Y%m%d%H%M%S')}"

        # Generate template
        generator = IaCTemplateGenerator()
        template_content = generator.generate_terraform_template(config)
        checksum = self.calculate_checksum(template_content)

        # Create deployment record
        deployment = DeploymentRecord(
            id=deployment_id,
            environment=environment,
            template_name='terraform',
            status=DeploymentStatus.INITIALIZED.value,
            resources_created=[],
            resources_destroyed=[],
            timestamp=datetime.now(),
            checksum=checksum,
            version='1.0.0'
        )

        # Simulate resource creation
        resource_types = ['aws_instance', 'aws_security_group', 'aws_vpc']
        for i, res_type in enumerate(resource_types):
            resource = ResourceInfo(
                id=f"{res_type}-{random.randint(1000, 9999)}",
                type=res_type,
                name=f"{res_type}-{i+1}",
                deployment_id=deployment_id,
                region=config.get('region', 'us-east-1'),
                tags=config.get('tags', {}),
                created_at=datetime.now(),
                status='created'
            )
            self.resources.append(resource)
            deployment.resources_created.append(resource.id)

        deployment.status = DeploymentStatus.APPLIED.value
        self.deployments.append(deployment)

        self._save_deployments()
        self._save_resources()

        logger.info("✓ Created Terraform deployment: %s", deployment_id)
        return deployment_id

    def create_cloudformation_deployment(self, environment: str, config: Dict[str, Any]) -> Optional[str]:
        """Create a CloudFormation deployment"""
        deployment_id = f"cf-{environment}-{datetime.now().strftime('%Y%m%d%H%M%S')}"

        generator = IaCTemplateGenerator()
        template_content = generator.generate_cloudformation_template(config)
        checksum = self.calculate_checksum(template_content)

        deployment = DeploymentRecord(
            id=deployment_id,
            environment=environment,
            template_name='cloudformation',
            status=DeploymentStatus.INITIALIZED.value,
            resources_created=[],
            resources_destroyed=[],
            timestamp=datetime.now(),
            checksum=checksum,
            version='1.0.0'
        )

        resource = ResourceInfo(
            id=f"stack-{random.randint(10000, 99999)}",
            type='CloudFormation::Stack',
            name=f"stack-{environment}",
            deployment_id=deployment_id,
            region=config.get('region', 'us-east-1'),
            tags=config.get('tags', {}),
            created_at=datetime.now(),
            status='created'
        )

        self.resources.append(resource)
        deployment.resources_created.append(resource.id)
        deployment.status = DeploymentStatus.APPLIED.value
        self.deployments.append(deployment)

        self._save_deployments()
        self._save_resources()

        logger.info("✓ Created CloudFormation deployment: %s", deployment_id)
        return deployment_id

    def create_kubernetes_deployment(self, environment: str, config: Dict[str, Any]) -> Optional[str]:
        """Create a Kubernetes deployment"""
        deployment_id = f"k8s-{environment}-{datetime.now().strftime('%Y%m%d%H%M%S')}"

        generator = IaCTemplateGenerator()
        template_content = generator.generate_kubernetes_yaml(config)
        checksum = self.calculate_checksum(template_content)

        deployment = DeploymentRecord(
            id=deployment_id,
            environment=environment,
            template_name='kubernetes',
            status=DeploymentStatus.INITIALIZED.value,
            resources_created=[],
            resources_destroyed=[],
            timestamp=datetime.now(),
            checksum=checksum,
            version='1.0.0'
        )

        # Create Deployment and Service resources
        for res_type in ['Deployment', 'Service']:
            resource = ResourceInfo(
                id=f"k8s-{res_type.lower()}-{random.randint(1000, 9999)}",
                type=f"kubernetes::{res_type}",
                name=f"{config.get('app_name', 'app')}-{res_type.lower()}",
                deployment_id=deployment_id,
                region='kubernetes',
                tags=config.get('tags', {}),
                created_at=datetime.now(),
                status='created'
            )
            self.resources.append(resource)
            deployment.resources_created.append(resource.id)

        deployment.status = DeploymentStatus.APPLIED.value
        self.deployments.append(deployment)

        self._save_deployments()
        self._save_resources()

        logger.info("✓ Created Kubernetes deployment: %s", deployment_id)
        return deployment_id

    def save_template(self, name: str, content: str, language: str):
        """Save a template"""
        checksum = self.calculate_checksum(content)

        template = TemplateFile(
            name=name,
            content=content,
            language=language,
            checksum=checksum,
            created_at=datetime.now()
        )

        self.templates[name] = template
        self._save_templates()

        logger.info("✓ Saved template: %s", name)

    def list_deployments(self, environment: Optional[str] = None) -> List[DeploymentRecord]:
        """List deployments"""
        if environment:
            return [d for d in self.deployments if d.environment == environment]
        return self.deployments

    def get_deployment_resources(self, deployment_id: str) -> List[ResourceInfo]:
        """Get resources for a deployment"""
        return [r for r in self.resources if r.deployment_id == deployment_id]

    def generate_drift_report(self) -> Dict[str, Any]:
        """Generate infrastructure drift report"""
        report = {
            'total_deployments': len(self.deployments),
            'by_status': {},
            'by_environment': {},
            'by_template_type': {},
            'total_resources': len(self.resources),
            'resources_by_type': {},
            'recent_deployments': []
        }

        for deployment in self.deployments:
            report['by_status'][deployment.status] = report['by_status'].get(deployment.status, 0) + 1
            report['by_environment'][deployment.environment] = report['by_environment'].get(deployment.environment, 0) + 1
            report['by_template_type'][deployment.template_name] = report['by_template_type'].get(deployment.template_name, 0) + 1

        for resource in self.resources:
            report['resources_by_type'][resource.type] = report['resources_by_type'].get(resource.type, 0) + 1

        report['recent_deployments'] = [
            {
                'id': d.id,
                'environment': d.environment,
                'template_name': d.template_name,
                'status': d.status,
                'timestamp': d.timestamp.isoformat(),
                'resources_count': len([r for r in self.resources if r.deployment_id == d.id])
            }
            for d in sorted(self.deployments, key=lambda x: x.timestamp, reverse=True)[:10]
        ]

        return report

    def export_deployment(self, deployment_id: str, filename: str):
        """Export deployment details to JSON"""
        deployment = next((d for d in self.deployments if d.id == deployment_id), None)

        if not deployment:
            logger.error("Deployment %s not found", deployment_id)
            return

        resources = self.get_deployment_resources(deployment_id)

        export_data = {
            'deployment': {
                'id': deployment.id,
                'environment': deployment.environment,
                'template_name': deployment.template_name,
                'status': deployment.status,
                'timestamp': deployment.timestamp.isoformat(),
                'version': deployment.version,
                'checksum': deployment.checksum
            },
            'resources': [
                {
                    'id': r.id,
                    'type': r.type,
                    'name': r.name,
                    'region': r.region,
                    'status': r.status,
                    'tags': r.tags,
                    'created_at': r.created_at.isoformat()
                }
                for r in resources
            ]
        }

        with open(filename, 'w') as f:
            json.dump(export_data, f, indent=2)

        logger.info("✓ Exported deployment to %s", filename)

def main():
    """Main execution function"""
    print("=" * 70)
    print(" Infrastructure as Code Manager - Standalone Demo")
    print("=" * 70)
    print()

    # Initialize IaC Manager
    iac_manager = IaCManager('./infrastructure')

    print("📋 Creating deployments...")
    print()

    # Create Terraform deployment
    tf_config = {
        'environment': 'production',
        'project': 'webapp',
        'region': 'us-east-1',
        'instance_type': 't2.micro',
        'ami': 'ami-0c55b159cbfafe1f0',
        'tags': {'Owner': 'DevOps', 'Project': 'WebApp'}
    }

    tf_id = iac_manager.create_terraform_deployment('production', tf_config)
    print(f"✓ Created Terraform deployment: {tf_id}")
    print()

    # Create CloudFormation deployment
    cf_config = {
        'environment': 'staging',
        'project': 'api',
        'region': 'eu-west-1',
        'instance_type': 't2.small',
        'tags': {'Owner': 'Backend', 'Project': 'API'}
    }

    cf_id = iac_manager.create_cloudformation_deployment('staging', cf_config)
    print(f"✓ Created CloudFormation deployment: {cf_id}")
    print()

    # Create Kubernetes deployment
    k8s_config = {
        'environment': 'production',
        'app_name': 'microservice',
        'namespace': 'default',
        'replicas': 3,
        'image': 'nginx:latest',
        'port': 8080,
        'tags': {'Owner': 'Platform', 'Project': 'Microservices'}
    }

    k8s_id = iac_manager.create_kubernetes_deployment('production', k8s_config)
    print(f"✓ Created Kubernetes deployment: {k8s_id}")
    print()

    # List deployments by environment
    print("=" * 70)
    print(" Deployments by Environment")
    print("=" * 70)

    for env in ['production', 'staging']:
        deployments = iac_manager.list_deployments(env)
        print(f"\n{env.upper()}: {len(deployments)} deployments")
        for dep in deployments:
            print(f"  - {dep.id}")
            print(f"    Template: {dep.template_name}, Status: {dep.status}")

    print()

    # Show resources for first deployment
    if iac_manager.deployments:
        first_dep = iac_manager.deployments[0]
        print("=" * 70)
        print(f" Resources for {first_dep.id}")
        print("=" * 70)
        resources = iac_manager.get_deployment_resources(first_dep.id)
        print(f"\nTotal resources: {len(resources)}")
        for resource in resources:
            print(f"  - {resource.type}: {resource.name} ({resource.status})")

    print()

    # Generate drift report
    print("=" * 70)
    print(" Infrastructure Drift Report")
    print("=" * 70)
    report = iac_manager.generate_drift_report()
    print(json.dumps(report, indent=2))
    print()

    # Export deployment
    if iac_manager.deployments:
        first_dep = iac_manager.deployments[0]
        iac_manager.export_deployment(first_dep.id, 'deployment_export.json')
        print()

    print("=" * 70)
    print(" Demo completed successfully!")
    print("=" * 70)

if __name__ == "__main__":
    main()